<?php

if ( $foo = 1 ) {
	# code...
} elseif ( $foo += 1 ) {
	# code...
} elseif ( $foo *= $bar ) {
	# code...
} elseif ( $foo > 1 || $bar < 1 || $foobar = 1 ) {
	# code...
} elseif ( $bar = $foo->foo() ) {
	# code...
}

while ( $foo = foo() ) {
	# code...
}
